# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AddHostDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddHostDialog(object):
    def setupUi(self, AddHostDialog):
        AddHostDialog.setObjectName("AddHostDialog")
        AddHostDialog.resize(357, 216)
        self.buttonBox = QtWidgets.QDialogButtonBox(AddHostDialog)
        self.buttonBox.setGeometry(QtCore.QRect(10, 180, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.formLayoutWidget = QtWidgets.QWidget(AddHostDialog)
        self.formLayoutWidget.setGeometry(QtCore.QRect(19, 19, 321, 148))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 6, 0, 6)
        self.formLayout.setHorizontalSpacing(10)
        self.formLayout.setVerticalSpacing(12)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.hostInput = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.hostInput.setObjectName("hostInput")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.hostInput)
        self.usernameInput = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.usernameInput.setObjectName("usernameInput")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.usernameInput)
        self.passwordInput = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.passwordInput.setObjectName("passwordInput")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.passwordInput)
        self.portInput = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.portInput.setObjectName("portInput")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.portInput)

        self.retranslateUi(AddHostDialog)
        self.buttonBox.accepted.connect(AddHostDialog.accept)
        self.buttonBox.rejected.connect(AddHostDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(AddHostDialog)

        ########## ONLY DEBUG
        self.portInput.setText('22')
        self.usernameInput.setText('root')
        self.hostInput.setText('192.168.1.1')
        self.passwordInput.setText('nevermind')
        ########## ONLY DEBUG

    def retranslateUi(self, AddHostDialog):
        _translate = QtCore.QCoreApplication.translate
        AddHostDialog.setWindowTitle(_translate("AddHostDialog", "Add a host"))
        self.label.setText(_translate("AddHostDialog", "Host"))
        self.label_2.setText(_translate("AddHostDialog", "Username"))
        self.label_3.setText(_translate("AddHostDialog", "Password"))
        self.label_4.setText(_translate("AddHostDialog", "Port"))
