# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ChangeNameDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(372, 145)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(20, 100, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.filenameLineEdit = QtWidgets.QLineEdit(Dialog)
        self.filenameLineEdit.setGeometry(QtCore.QRect(10, 50, 351, 25))
        self.filenameLineEdit.setObjectName("filenameLineEdit")
        self.optionLabel = QtWidgets.QLabel(Dialog)
        self.optionLabel.setGeometry(QtCore.QRect(10, 20, 101, 17))
        self.optionLabel.setObjectName("optionLabel")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Change name"))
        self.optionLabel.setText(_translate("Dialog", "New file name"))
