# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ConnectionPropertiesDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 244)
        self.formLayoutWidget = QtWidgets.QWidget(Dialog)
        self.formLayoutWidget.setGeometry(QtCore.QRect(19, 19, 361, 174))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.statusLine = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.statusLine.setReadOnly(True)
        self.statusLine.setObjectName("statusLine")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.statusLine)
        self.hostLine = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.hostLine.setReadOnly(True)
        self.hostLine.setObjectName("hostLine")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.hostLine)
        self.usernameLine = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.usernameLine.setReadOnly(True)
        self.usernameLine.setObjectName("usernameLine")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.usernameLine)
        self.passwordLine = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.passwordLine.setReadOnly(True)
        self.passwordLine.setObjectName("passwordLine")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.passwordLine)
        self.portLine = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.portLine.setReadOnly(True)
        self.portLine.setObjectName("portLine")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.portLine)
        self.okButton = QtWidgets.QPushButton(Dialog)
        self.okButton.setGeometry(QtCore.QRect(290, 200, 89, 25))
        self.okButton.setObjectName("okButton")
        self.connectButton = QtWidgets.QPushButton(Dialog)
        self.connectButton.setGeometry(QtCore.QRect(20, 200, 89, 25))
        self.connectButton.setObjectName("connectButton")
        self.disconnectButton = QtWidgets.QPushButton(Dialog)
        self.disconnectButton.setGeometry(QtCore.QRect(120, 200, 89, 25))
        self.disconnectButton.setObjectName("disconnectButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Connection properties"))
        self.label.setText(_translate("Dialog", "Properties"))
        self.label_2.setText(_translate("Dialog", "Status"))
        self.label_3.setText(_translate("Dialog", "Host"))
        self.label_4.setText(_translate("Dialog", "Username"))
        self.label_5.setText(_translate("Dialog", "Password"))
        self.label_6.setText(_translate("Dialog", "Port"))
        self.okButton.setText(_translate("Dialog", "OK"))
        self.connectButton.setText(_translate("Dialog", "Connect"))
        self.disconnectButton.setText(_translate("Dialog", "Disconnect"))
