# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(932, 637)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.catalogTreeWidgetLeft = QtWidgets.QTreeWidget(self.centralwidget)
        self.catalogTreeWidgetLeft.setGeometry(QtCore.QRect(10, 190, 451, 401))
        self.catalogTreeWidgetLeft.setColumnCount(5)
        self.catalogTreeWidgetLeft.setObjectName("catalogTreeWidgetLeft")
        self.catalogTreeWidgetLeft.headerItem().setText(0, "Name")
        self.partitionsListWidgetLeft = QtWidgets.QListWidget(self.centralwidget)
        self.partitionsListWidgetLeft.setGeometry(QtCore.QRect(10, 30, 451, 151))
        self.partitionsListWidgetLeft.setObjectName("partitionsListWidgetLeft")
        self.partitionsListWidgetRight = QtWidgets.QListWidget(self.centralwidget)
        self.partitionsListWidgetRight.setGeometry(QtCore.QRect(470, 30, 451, 151))
        self.partitionsListWidgetRight.setObjectName("partitionsListWidgetRight")
        self.catalogTreeWidgetRight = QtWidgets.QTreeWidget(self.centralwidget)
        self.catalogTreeWidgetRight.setGeometry(QtCore.QRect(470, 190, 451, 401))
        self.catalogTreeWidgetRight.setColumnCount(5)
        self.catalogTreeWidgetRight.setObjectName("catalogTreeWidgetRight")
        self.catalogTreeWidgetRight.headerItem().setText(0, "Name")
        self.connectionInfoLabelLeft = QtWidgets.QLabel(self.centralwidget)
        self.connectionInfoLabelLeft.setGeometry(QtCore.QRect(10, 10, 451, 17))
        self.connectionInfoLabelLeft.setObjectName("connectionInfoLabelLeft")
        self.connectionInfoLabelRight = QtWidgets.QLabel(self.centralwidget)
        self.connectionInfoLabelRight.setGeometry(QtCore.QRect(470, 10, 451, 17))
        self.connectionInfoLabelRight.setObjectName("connectionInfoLabelRight")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 932, 22))
        self.menubar.setObjectName("menubar")
        self.menuHosts = QtWidgets.QMenu(self.menubar)
        self.menuHosts.setObjectName("menuHosts")
        self.menuConnection = QtWidgets.QMenu(self.menubar)
        self.menuConnection.setObjectName("menuConnection")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionHost_list = QtWidgets.QAction(MainWindow)
        self.actionHost_list.setObjectName("actionHost_list")
        self.actionSaved_hosts = QtWidgets.QAction(MainWindow)
        self.actionSaved_hosts.setObjectName("actionSaved_hosts")
        self.actionConnect_to = QtWidgets.QAction(MainWindow)
        self.actionConnect_to.setObjectName("actionConnect_to")
        self.actionLeft_window_connection = QtWidgets.QAction(MainWindow)
        self.actionLeft_window_connection.setObjectName("actionLeft_window_connection")
        self.actionConnection_properties = QtWidgets.QAction(MainWindow)
        self.actionConnection_properties.setObjectName("actionConnection_properties")
        self.actionConnect_right = QtWidgets.QAction(MainWindow)
        self.actionConnect_right.setObjectName("actionConnect_right")
        self.actionRight_window_connection = QtWidgets.QAction(MainWindow)
        self.actionRight_window_connection.setObjectName("actionRight_window_connection")
        self.menuHosts.addAction(self.actionHost_list)
        self.menuHosts.addAction(self.actionSaved_hosts)
        self.menuConnection.addAction(self.actionLeft_window_connection)
        self.menuConnection.addAction(self.actionRight_window_connection)
        self.menubar.addAction(self.menuConnection.menuAction())
        self.menubar.addAction(self.menuHosts.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Remote hosts disk management"))
        self.catalogTreeWidgetLeft.headerItem().setText(1, _translate("MainWindow", "Rights"))
        self.catalogTreeWidgetLeft.headerItem().setText(2, _translate("MainWindow", "Created"))
        self.catalogTreeWidgetLeft.headerItem().setText(3, _translate("MainWindow", "Owner"))
        self.catalogTreeWidgetLeft.headerItem().setText(4, _translate("MainWindow", "Creator"))
        self.catalogTreeWidgetRight.headerItem().setText(1, _translate("MainWindow", "Rights"))
        self.catalogTreeWidgetRight.headerItem().setText(2, _translate("MainWindow", "Created"))
        self.catalogTreeWidgetRight.headerItem().setText(3, _translate("MainWindow", "Owner"))
        self.catalogTreeWidgetRight.headerItem().setText(4, _translate("MainWindow", "Creator"))
        self.connectionInfoLabelLeft.setText(_translate("MainWindow", "Disconnected"))
        self.connectionInfoLabelRight.setText(_translate("MainWindow", "Disconnected"))
        self.menuHosts.setTitle(_translate("MainWindow", "Hosts"))
        self.menuConnection.setTitle(_translate("MainWindow", "Connection"))
        self.actionHost_list.setText(_translate("MainWindow", "Add a host"))
        self.actionSaved_hosts.setText(_translate("MainWindow", "Saved hosts"))
        self.actionConnect_to.setText(_translate("MainWindow", "Connect left"))
        self.actionLeft_window_connection.setText(_translate("MainWindow", "Left window connection properties"))
        self.actionConnection_properties.setText(_translate("MainWindow", "Connection properties"))
        self.actionConnect_right.setText(_translate("MainWindow", "Connect right"))
        self.actionRight_window_connection.setText(_translate("MainWindow", "Right window connection properties"))
